version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - goimports
    - misspell

issues:
  exclude:
    rules: # 注意：v2 改成了多嵌套一层 exclude，下面才是 rules
      - path: _test\.go
        linters:
          - errcheck
